SELECT * FROM SUPER_MARKET; 
DESC SUPER_MARKET;
SELECT SUM (SALES) AS TOTAL_SALES FROM SUPER_MARKET;
SELECT SUM (QUANTITY) AS TOTAL_QUANTITY FROM SUPER_MARKET;
SELECT SUM(PROFIT) AS TOTAL_PROFIT FROM SUPER_MARKET;
SELECT DISTINCT (YEAR) FROM SUPER_MARKET;
SELECT DISTINCT (SHIP_MODE) FROM SUPER_MARKET;
SELECT DISTINCT(CATEGORY) FROM SUPER_MARKET;
SELECT DISTINCT(SUB_CATEGORY) FROM SUPER_MARKET;
SELECT DISTINCT(SEGMENT) FROM super_market;
SELECT DISTINCT(MARKET) FROM super_market;

---.... TOTAL SALES BY MARKET....---
SELECT DISTINCT
MARKET, SUM(SALES) AS TOTAL_SALES
FROM SUPER_MARKET
GROUP BY MARKET
ORDER BY TOTAL_SALES;

----....TOTAL SALES, TOTAL PROFIT, BY COUNTRY....---

SELECT COUNTRY, SUM(SALES) AS TOTAL_SALES,
TO_CHAR (SUM(PROFIT),'99999.99') AS TOTAL_PROFIT
FROM super_market
GROUP BY COUNTRY
ORDER BY TOTAL_SALES DESC;

---....TOTAL SALES, TOTAL PROFIT BY CATEGORY....---

SELECT DISTINCT
    YEAR,
    CATEGORY,
    SUM(SALES) AS TOTAL_SALES,
    TO_CHAR(SUM(PROFIT), '9999999.99') AS TOTAL_PROFIT
FROM 
    SUPER_MARKET
GROUP BY 
    YEAR, CATEGORY
ORDER BY 
    YEAR ASC;




 ---....CATEGORY TO SUB-CATEGORY....---   
    SELECT DISTINCT
    s.SUB_CATEGORY AS Subcategory,
    c.CATEGORY AS Category
FROM 
    SUPER_MARKET s
JOIN 
    SUPER_MARKET c ON s.CATEGORY = c.CATEGORY
WHERE 
    s.SUB_CATEGORY IS NOT NULL
ORDER BY 
    CATEGORY DESC;
    
---... TOTAL & AVERAGE SALES, PROFIT, QUANTITY, SHIPPING-COST ....---

        SELECT YEAR,
    AVG(SALES) AS AVG_SALES,
    SUM(SALES) AS TOTAL_SALES,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    AVG(QUANTITY) AS AVG_QUANTITY,
    SUM(PROFIT) AS TOTAL_PROFIT,
    SUM(SHIPPING_COST) AS TOTAL_SHIPPING_COST,
    AVG(SHIPPING_COST) AS AVG_SHIPPING_COST
FROM 
    SUPER_MARKET 
GROUP BY 
    YEAR
ORDER BY 
    YEAR;
    
---... TOTAL & AVERAGE SALES, PROFIT, QUANTITY, SHIPPING-COST BY YEAR ....---

SELECT 
    CASE WHEN GROUPING(YEAR) = 1 THEN 'Total' ELSE TO_CHAR(YEAR) END AS YEAR,
    TO_CHAR(AVG(SALES), '999999999.99') AS AVG_SALES,
    SUM(SALES) AS TOTAL_SALES,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    TO_CHAR(AVG(QUANTITY), '999999999.99') AS AVG_QUANTITY,
    SUM(PROFIT) AS TOTAL_PROFIT,
    SUM(SHIPPING_COST) AS TOTAL_SHIPPING_COST,
    TO_CHAR(AVG(SHIPPING_COST), '999999999.99') AS AVG_SHIPPING_COST
FROM 
    SUPER_MARKET 
GROUP BY 
    ROLLUP(YEAR)
ORDER BY 
    YEAR;

---.... TOTAL SALES, TOTAL PROFIT BY SEGMENT AND YEAR....---

SELECT DISTINCT
YEAR, SEGMENT, SUM(SALES) AS TOTAL_SALES,
TO_CHAR (SUM(PROFIT),'99999.99') AS TOTAL_PROFIT
FROM super_market 
GROUP BY YEAR, SEGMENT
ORDER BY YEAR;



